# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: "3.9"
services:
  nginx-ga-middleware:
    container_name: nginx-ga-middleware
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx:/etc/nginx
      - ./nginx/share/index.html:/usr/share/nginx/html/index.html
    restart: on-failure:5
    networks:
      ga-middleware-network:
        ipv4_address: 128.255.0.2
  flask-ga-middleware:
    container_name: flask-ga-middleware
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - nginx-ga-middleware
    restart: always
    networks:
      ga-middleware-network:
        ipv4_address: 128.255.0.3
networks:
  ga-middleware-network:
    ipam:
      config:
        - subnet: 128.255.0.0/29
